### ISSUE TITLE
Isolate asyncio loops and exec calls to prevent main.py from crashing when a plugin crashes.

### ISSUE THREAD

**Issue by pastaq** [SteamDeckHomebrew/decky-loader#127]
Currently there exists the possibility of a single plugin error causing the entire decky-loader instance to halt. This could happen for a myriad of reasons, I.E. two conflicting plugins, other software conflicting with a plugin, incompatible configurations or hardware, etc. In such a case that the mere loading of a plugin will cause the issue, an irrevocable boot failure loop could occur where a user is unable to uninstall an incompatible plugin through the UI.

I've only taken a cursory review of the execution path so there may be incorrect assumption ahead. Executing asyncio loops or exec calls should handle exceptions in these cases by logging the error and sending a signal to decky to halt the loop and unload the plugin. The signaling should likely be sent by the PluginWrapper and the loader should respond to the signal to "quarantine" the offending plugin in some way, essentially disabling it until reloaded by the user manually. It would also need to stop the execution loop for that plugin and remove it from the reload queue to bypass a RuntimeError in main.py. This will ensure that a single conflict with an ever growing userbase and plugin database is easier to manage going forward. 

Example:
In this scenario I was testing a plugin designed exclusively for the steam deck on SteamOS 3.x using an OXP Mini on ChimeraOS

```
Aug 03 22:21:59 chimeraos PluginLoader[652]: [browser][INFO]: Installed PowerTools (Version: 0.7.0)
Aug 03 22:21:59 chimeraos PluginLoader[7062]: Process Process-17:
Aug 03 22:21:59 chimeraos PluginLoader[7062]: Traceback (most recent call last):
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "multiprocessing/process.py", line 315, in _bootstrap
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "multiprocessing/process.py", line 108, in run
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "plugin.py", line 49, in _init
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "/home/gamer/homebrew/plugins/PowerTools/main.py", line 30, in <module>
Aug 03 22:21:59 chimeraos PluginLoader[7062]:     import server as pt_server
Aug 03 22:21:59 chimeraos PluginLoader[7062]:   File "/home/gamer/homebrew/plugins/PowerTools/server.py", line 14, in <module>
Aug 03 22:21:59 chimeraos PluginLoader[7062]:     os.mkdir(SETTINGS_DIR)
Aug 03 22:21:59 chimeraos PluginLoader[7062]: FileNotFoundError: [Errno 2] No such file or directory: '/home/deck/.config/powertools'
Aug 03 22:23:28 chimeraos PluginLoader[652]: [base_events][ERROR]: Unclosed client session
Aug 03 22:23:28 chimeraos PluginLoader[652]: client_session: <aiohttp.client.ClientSession object at 0x7fb26193e170>
Aug 03 22:25:02 chimeraos PluginLoader[652]: [base_events][ERROR]: Unclosed client session
Aug 03 22:25:02 chimeraos PluginLoader[652]: client_session: <aiohttp.client.ClientSession object at 0x7fb261deb880>
Aug 03 22:26:33 chimeraos systemd[1]: Stopping SteamDeck Plugin Loader...
Aug 03 22:27:33 chimeraos PluginLoader[652]: Traceback (most recent call last):
Aug 03 22:27:33 chimeraos PluginLoader[652]:   File "plugin.py", line 13, in <module>
Aug 03 22:27:33 chimeraos PluginLoader[652]:   File "multiprocessing/context.py", line 243, in set_start_method
Aug 03 22:27:33 chimeraos PluginLoader[652]: RuntimeError: context has already been set
Aug 03 22:27:33 chimeraos PluginLoader[652]: [652] Failed to execute script 'plugin' due to unhandled exception!
Aug 03 22:27:33 chimeraos systemd[1]: plugin_loader.service: Main process exited, code=exited, status=1/FAILURE
Aug 03 22:27:33 chimeraos systemd[1]: plugin_loader.service: Failed with result 'exit-code'.
Aug 03 22:27:33 chimeraos systemd[1]: Stopped SteamDeck Plugin Loader.
Aug 03 22:27:33 chimeraos systemd[1]: plugin_loader.service: Consumed 2.998s CPU time.
```

**Comment by AAGaming00** [comment]
Should be fixed as of c774451
