### ISSUE TITLE
Failed Install - Steam Deck OLED

### ISSUE THREAD

**Issue by cashcon57** [SteamDeckHomebrew/decky-loader#567]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [common issues section in the readme file](https://github.com/SteamDeckHomebrew/decky-loader#-common-issues)
- [X] I have attached logs to this bug report (failure to include logs will mean your issue may not be responded to).

### Bug Report Description

When I attempt to install deckyloader on my 1TB Steam Deck OLED by placing the pluginloader application on the desktop and executing it, then entering admin password, nothing happens. I decided to open the app with Konsole, and I got the log attached.

### Expected Behaviour

Click, then install happens.

### SteamOS version

3.5.7 Stable

### Selected Update Channel

Stable

### Logs

[main][WARNING]: decky is running as an unprivileged user, this is not
officially supported and may cause issues
[loader][INFO]: plugin_path: /home/deck/plugins
[helpers][WARNING]: Failed to execute get_loader_version(): [Errno 2]
No such file or directory: '/home/deck/Desktop/.loader.version'
[loader][INFO]: import plugins from /home/deck/plugins
[loader][INFO]: Hot reload enabled
[base_events][ERROR]: unhandled exception during asyncio.run() shutdow
n
task: <Task finished name='Task-4' coro=<\_run\_app() done, defined at a iohttp/web.py:289> exception=OSError(98, "error while attempting to bi
nd on address ('127.0.0.1', 1337): address already in use")>
Traceback (most recent call last):
 File "aiohttp/web.py", line 516, in run_app
 File "asyncio/base_events.py", line 646, in run_until_complete
 File "aiohttp/web.py", line 415, in _run_app
 File "aiohttp/web_runner.py", line 121, in start
 File "asyncio/base_events.py", line 1505, in create_server
OSError: [Errno 98] error while attempting to bind on address ('127.0.
0.1', 1337): address already in use
Traceback (most recent call last):
 File "main.py", line 4, in <module>
 File "src/main.py", line 192, in main
 File "src/main.py", line 170, in run
 File "aiohttp/web.py", line 516, in run_app
 File "asyncio/base_events.py", line 646, in run_until_complete
 File "aiohttp/web.py", line 415, in _run_app
 File "aiohttp/web_runner.py", line 121, in start
 File "asyncio/base_events.py", line 1505, in create_server
OSError: [Errno 98] error while attempting to bind on address ('127.0.
0.1', 1337): address already in use
[7258] Failed to execute script 'main' due to unhandled exception!
main][WARNING]: decky is running as an unprivileged user, this is not
officially supported and may cause issues
[loader][INFO]: plugin_path: /home/deck/plugins
[helpers][WARNING]: Failed to execute get_loader_version(): [Errno 2]
No such file or directory: '/home/deck/Desktop/.loader.version'
[loader][INFO]: import plugins from /home/deck/plugins
[loader][INFO]: Hot reload enabled
[base_events][ERROR]: unhandled exception during asyncio.run() shutdow
n
task: <Task finished name='Task-4' coro=<\_run\_app() done, defined at a iohttp/web.py:289> exception=OSError(98, "error while attempting to bi
nd on address ('127.0.0.1', 1337): address already in use")>
Traceback (most recent call last):
 File "aiohttp/web.py", line 516, in run_app
 File "asyncio/base_events.py", line 646, in run_until_complete
 File "aiohttp/web.py", line 415, in _run_app
 File "aiohttp/web_runner.py", line 121, in start
 File "asyncio/base_events.py", line 1505, in create_server
OSError: [Errno 98] error while attempting to bind on address ('127.0.
0.1', 1337): address already in use
Traceback (most recent call last):
 File "main.py", line 4, in <module>
 File "src/main.py", line 192, in main
 File "src/main.py", line 170, in run
 File "aiohttp/web.py", line 516, in run_app
 File "asyncio/base_events.py", line 646, in run_until_complete
 File "aiohttp/web.py", line 415, in _run_app
 File "aiohttp/web_runner.py", line 121, in start
 File "asyncio/base_events.py", line 1505, in create_server
OSError: [Errno 98] error while attempting to bind on address ('127.0.
0.1', 1337): address already in use
[7258] Failed to execute script 'main' due to unhandled exception!

**Comment by TrainDoctor** [comment]
It looks like you're using an Application such as synching that's occupying port 8080. Disable that app and let me know if the behavior changes.

**Comment by AAGaming00** [comment]
download the installer .desktop from https://decky.xyz and use that, not the pluginloader app

**Comment by cashcon57** [comment]
@AAGaming00 that is what I'm talking about. I apologize for not using the correct words.

**Comment by AAGaming00** [comment]
your logs show that you are trying to run the pluginloader app, not the installer .desktop

**Comment by cashcon57** [comment]
@AAGaming00 I see what you mean. My apologies. I downloaded directly from the github page. It now works. Thank you and @TrainDoctor for your prompt help with my self-inflicted issue. Thank you for your time!
